version: '3.4'
services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    rabbitmq:
        image: "rabbitmq:alpine"
        ports:
            - "4369:4369"
            - "25672:25672"
            - "5672:5672"
            - "5671:5671"
volumes:
  git:
    driver: local